const garminMeasurementMapping = {
    // Check-in Measurements
    'weight': { targetType: 'check_in', field: 'weight', dataType: 'numeric', measurementType: 'kg' },
    'body_fat_percentage': { targetType: 'check_in', field: 'body_fat_percentage', dataType: 'numeric', measurementType: '%' },
    'bmi': { targetType: 'custom', name: 'BMI', dataType: 'numeric', measurementType: 'N/A', frequency: 'Daily' },
    'body_water_percentage': { targetType: 'check_in', field: 'body_water_percentage', dataType: 'numeric', measurementType: '%' },
    'bone_mass': { targetType: 'custom', name: 'Bone Mass', dataType: 'numeric', measurementType: 'kg', frequency: 'Daily' },
    'muscle_mass': { targetType: 'check_in', field: 'muscle_mass_kg', dataType: 'numeric', measurementType: 'kg' },
    'hydration': { targetType: 'check_in', field: 'water', dataType: 'numeric', measurementType: 'ml' },

    // Custom Measurements
    'resting_heart_rate': { targetType: 'custom', name: 'Resting Heart Rate', dataType: 'numeric', measurementType: 'bpm', frequency: 'Daily' },
    'sleep_duration': { targetType: 'custom', name: 'Sleep Duration', dataType: 'numeric', measurementType: 'minutes', frequency: 'Daily' },
    'stress_level': { targetType: 'custom', name: 'Stress Level', dataType: 'numeric', measurementType: 'N/A', frequency: 'Daily' },
    'average_respiration_rate': { targetType: 'custom', name: 'Average Respiration Rate', dataType: 'numeric', measurementType: 'brpm', frequency: 'Daily' },
    'average_spo2': { targetType: 'custom', name: 'Average SpO2', dataType: 'numeric', measurementType: '%', frequency: 'Daily' },
    'total_intensity_minutes': { targetType: 'custom', name: 'Total Intensity Minutes', dataType: 'numeric', measurementType: 'minutes', frequency: 'Daily' },
    'training_readiness_score': { targetType: 'custom', name: 'Training Readiness Score', dataType: 'integer', measurementType: 'N/A', frequency: 'Daily' },
    'training_status': { targetType: 'custom', name: 'Training Status', dataType: 'text', measurementType: 'N/A', frequency: 'Daily' },
    'vo2_max': { targetType: 'custom', name: 'VO2 Max', dataType: 'numeric', measurementType: 'mL/kg/min', frequency: 'Daily' },
    'average_overnight_hrv': { targetType: 'custom', name: 'Average Overnight HRV', dataType: 'numeric', measurementType: 'ms', frequency: 'Daily' },
    'lactate_threshold_hr': { targetType: 'custom', name: 'Lactate Threshold HR', dataType: 'numeric', measurementType: 'bpm', frequency: 'Daily' },
    'endurance_score': { targetType: 'custom', name: 'Endurance Score', dataType: 'numeric', measurementType: 'N/A', frequency: 'Daily' },
    'hill_score': { targetType: 'custom', name: 'Hill Score', dataType: 'numeric', measurementType: 'N/A', frequency: 'Daily' },
    'race_prediction_5k': { targetType: 'custom', name: '5K Race Prediction', dataType: 'numeric', measurementType: 'seconds', frequency: 'Daily' },
    'blood_pressure': { targetType: 'custom', name: 'Blood Pressure', dataType: 'text', measurementType: 'mmHg/bpm', frequency: 'Daily' },
    'body_battery_highest': { targetType: 'custom', name: 'Body Battery Highest', dataType: 'numeric', measurementType: 'N/A', frequency: 'Daily' },
    'body_battery_lowest': { targetType: 'custom', name: 'Body Battery Lowest', dataType: 'numeric', measurementType: 'N/A', frequency: 'Daily' },
    'body_battery_at_wake': { targetType: 'custom', name: 'Body Battery At Wake', dataType: 'numeric', measurementType: 'N/A', frequency: 'Daily' },
    'body_battery_charged': { targetType: 'custom', name: 'Body Battery Charged', dataType: 'numeric', measurementType: 'N/A', frequency: 'Daily' },
    'body_battery_drained': { targetType: 'custom', name: 'Body Battery Drained', dataType: 'numeric', measurementType: 'N/A', frequency: 'Daily' },
    'total_distance': { targetType: 'custom', name: 'Total Distance', dataType: 'numeric', measurementType: 'km', frequency: 'Daily' },
    'highly_active_seconds': { targetType: 'custom', name: 'Highly Active Minutes', dataType: 'numeric', measurementType: 'minutes', frequency: 'Daily' },
    'active_seconds': { targetType: 'custom', name: 'Active Minutes', dataType: 'numeric', measurementType: 'minutes', frequency: 'Daily' },
    'sedentary_seconds': { targetType: 'custom', name: 'Sedentary Minutes', dataType: 'numeric', measurementType: 'minutes', frequency: 'Daily' },
    'floors_ascended': { targetType: 'custom', name: 'Floors Ascended', dataType: 'integer', measurementType: 'floors', frequency: 'Daily' },
    'floors_descended': { targetType: 'custom', name: 'Floors Descended', dataType: 'integer', measurementType: 'floors', frequency: 'Daily' },
    'stress_duration_total': { targetType: 'custom', name: 'Stress Duration Total', dataType: 'numeric', measurementType: 'seconds', frequency: 'Daily' },
    'stress_duration_rest': { targetType: 'custom', name: 'Stress Duration Rest', dataType: 'numeric', measurementType: 'seconds', frequency: 'Daily' },
    'stress_duration_activity': { targetType: 'custom', name: 'Stress Duration Activity', dataType: 'numeric', measurementType: 'seconds', frequency: 'Daily' },
    'stress_duration_uncategorized': { targetType: 'custom', name: 'Stress Duration Uncategorized', dataType: 'numeric', measurementType: 'seconds', frequency: 'Daily' },
    'stress_duration_low': { targetType: 'custom', name: 'Stress Duration Low', dataType: 'numeric', measurementType: 'seconds', frequency: 'Daily' },
    'stress_duration_medium': { targetType: 'custom', name: 'Stress Duration Medium', dataType: 'numeric', measurementType: 'seconds', frequency: 'Daily' },
    'stress_duration_high': { targetType: 'custom', name: 'Stress Duration High', dataType: 'numeric', measurementType: 'seconds', frequency: 'Daily' },
    'stress_percentage_low': { targetType: 'custom', name: 'Stress Percentage Low', dataType: 'numeric', measurementType: '%', frequency: 'Daily' },
    'stress_percentage_medium': { targetType: 'custom', name: 'Stress Percentage Medium', dataType: 'numeric', measurementType: '%', frequency: 'Daily' },
    'stress_percentage_high': { targetType: 'custom', name: 'Stress Percentage High', dataType: 'numeric', measurementType: '%', frequency: 'Daily' },
    'visceral_fat_level': { targetType: 'check_in', field: 'visceral_fat_level', dataType: 'integer', measurementType: 'N/A' },
};

module.exports = garminMeasurementMapping;